# frozen_string_literal: true

module Deeprails
  module Models
    # @see Deeprails::Resources::Defend#submit_event
    class DefendSubmitEventParams < Deeprails::Internal::Type::BaseModel
      extend Deeprails::Internal::Type::RequestParameters::Converter
      include Deeprails::Internal::Type::RequestParameters

      # @!attribute model_input
      #   A dictionary of inputs sent to the LLM to generate output. This must contain a
      #   `user_prompt` field and an optional `context` field. Additional properties are
      #   allowed.
      #
      #   @return [Deeprails::Models::DefendSubmitEventParams::ModelInput]
      required :model_input, -> { Deeprails::DefendSubmitEventParams::ModelInput }

      # @!attribute model_output
      #   Output generated by the LLM to be evaluated.
      #
      #   @return [String]
      required :model_output, String

      # @!attribute model_used
      #   Model ID used to generate the output, like `gpt-4o` or `o3`.
      #
      #   @return [String]
      required :model_used, String

      # @!attribute run_mode
      #   Run mode for the workflow event. The run mode allows the user to optimize for
      #   speed, accuracy, and cost by determining which models are used to evaluate the
      #   event. Available run modes include `precision_plus`, `precision`, `smart`, and
      #   `economy`. Defaults to `smart`.
      #
      #   @return [Symbol, Deeprails::Models::DefendSubmitEventParams::RunMode]
      required :run_mode, enum: -> { Deeprails::DefendSubmitEventParams::RunMode }

      # @!attribute nametag
      #   An optional, user-defined tag for the event.
      #
      #   @return [String, nil]
      optional :nametag, String

      # @!method initialize(model_input:, model_output:, model_used:, run_mode:, nametag: nil, request_options: {})
      #   Some parameter documentations has been truncated, see
      #   {Deeprails::Models::DefendSubmitEventParams} for more details.
      #
      #   @param model_input [Deeprails::Models::DefendSubmitEventParams::ModelInput] A dictionary of inputs sent to the LLM to generate output. This must contain a
      #
      #   @param model_output [String] Output generated by the LLM to be evaluated.
      #
      #   @param model_used [String] Model ID used to generate the output, like `gpt-4o` or `o3`.
      #
      #   @param run_mode [Symbol, Deeprails::Models::DefendSubmitEventParams::RunMode] Run mode for the workflow event. The run mode allows the user to optimize for s
      #
      #   @param nametag [String] An optional, user-defined tag for the event.
      #
      #   @param request_options [Deeprails::RequestOptions, Hash{Symbol=>Object}]

      class ModelInput < Deeprails::Internal::Type::BaseModel
        # @!attribute user_prompt
        #
        #   @return [String]
        required :user_prompt, String

        # @!attribute context
        #
        #   @return [String, nil]
        optional :context, String

        # @!method initialize(user_prompt:, context: nil)
        #   A dictionary of inputs sent to the LLM to generate output. This must contain a
        #   `user_prompt` field and an optional `context` field. Additional properties are
        #   allowed.
        #
        #   @param user_prompt [String]
        #   @param context [String]
      end

      # Run mode for the workflow event. The run mode allows the user to optimize for
      # speed, accuracy, and cost by determining which models are used to evaluate the
      # event. Available run modes include `precision_plus`, `precision`, `smart`, and
      # `economy`. Defaults to `smart`.
      module RunMode
        extend Deeprails::Internal::Type::Enum

        PRECISION_PLUS = :precision_plus
        PRECISION = :precision
        SMART = :smart
        ECONOMY = :economy

        # @!method self.values
        #   @return [Array<Symbol>]
      end
    end
  end
end
