# frozen_string_literal: true

module Deeprails
  module Models
    # @see Deeprails::Resources::Defend#submit_and_stream_event_streaming
    class DefendSubmitAndStreamEventParams < Deeprails::Internal::Type::BaseModel
      extend Deeprails::Internal::Type::RequestParameters::Converter
      include Deeprails::Internal::Type::RequestParameters

      # @!attribute workflow_id
      #
      #   @return [String]
      required :workflow_id, String

      # @!attribute model_input
      #   The input provided to the model (e.g., prompt, messages).
      #
      #   @return [Hash{Symbol=>Object}]
      required :model_input, Deeprails::Internal::Type::HashOf[Deeprails::Internal::Type::Unknown]

      # @!attribute model_output
      #   The output generated by the model to be evaluated.
      #
      #   @return [String]
      required :model_output, String

      # @!attribute model_used
      #   The model that generated the output (e.g., "gpt-4", "claude-3").
      #
      #   @return [String]
      required :model_used, String

      # @!attribute run_mode
      #   The evaluation run mode. Streaming only supports fast, precision, and
      #   precision_codex.
      #
      #   @return [Symbol, Deeprails::Models::DefendSubmitAndStreamEventParams::RunMode]
      required :run_mode, enum: -> { Deeprails::DefendSubmitAndStreamEventParams::RunMode }

      # @!attribute stream
      #   Enable SSE streaming for real-time token feedback. Only supported for
      #   single-model run modes (fast, precision, precision_codex).
      #
      #   @return [Boolean, nil]
      optional :stream, Deeprails::Internal::Type::Boolean

      # @!attribute nametag
      #   Optional tag to identify this event.
      #
      #   @return [String, nil]
      optional :nametag, String

      # @!method initialize(workflow_id:, model_input:, model_output:, model_used:, run_mode:, stream: nil, nametag: nil, request_options: {})
      #   Some parameter documentations has been truncated, see
      #   {Deeprails::Models::DefendSubmitAndStreamEventParams} for more details.
      #
      #   @param workflow_id [String]
      #
      #   @param model_input [Hash{Symbol=>Object}] The input provided to the model (e.g., prompt, messages).
      #
      #   @param model_output [String] The output generated by the model to be evaluated.
      #
      #   @param model_used [String] The model that generated the output (e.g., "gpt-4", "claude-3").
      #
      #   @param run_mode [Symbol, Deeprails::Models::DefendSubmitAndStreamEventParams::RunMode] The evaluation run mode. Streaming only supports fast, precision, and
      #   precision\_
      #
      #   @param stream [Boolean] Enable SSE streaming for real-time token feedback. Only supported for single-mod
      #
      #   @param nametag [String] Optional tag to identify this event.
      #
      #   @param request_options [Deeprails::RequestOptions, Hash{Symbol=>Object}]

      # The evaluation run mode. Streaming only supports fast, precision, and
      # precision_codex.
      module RunMode
        extend Deeprails::Internal::Type::Enum

        FAST = :fast
        PRECISION = :precision
        PRECISION_CODEX = :precision_codex
        PRECISION_MAX = :precision_max
        PRECISION_MAX_CODEX = :precision_max_codex

        # @!method self.values
        #   @return [Array<Symbol>]
      end
    end
  end
end
