# frozen_string_literal: true

module Deeprails
  module Models
    # @see Deeprails::Resources::Defend#submit_event
    class DefendSubmitEventParams < Deeprails::Internal::Type::BaseModel
      extend Deeprails::Internal::Type::RequestParameters::Converter
      include Deeprails::Internal::Type::RequestParameters

      # @!attribute model_input
      #   A dictionary of inputs sent to the LLM to generate output. The dictionary must
      #   contain a `user_prompt` field. For the ground_truth_adherence guardrail metric,
      #   `ground_truth` should be provided.
      #
      #   @return [Deeprails::Models::DefendSubmitEventParams::ModelInput]
      required :model_input, -> { Deeprails::DefendSubmitEventParams::ModelInput }

      # @!attribute model_output
      #   Output generated by the LLM to be evaluated.
      #
      #   @return [String]
      required :model_output, String

      # @!attribute model_used
      #   Model ID used to generate the output, like `gpt-4o` or `o3`.
      #
      #   @return [String]
      required :model_used, String

      # @!attribute run_mode
      #   Run mode for the workflow event. The run mode allows the user to optimize for
      #   speed, accuracy, and cost by determining which models are used to evaluate the
      #   event. Available run modes include `precision_plus_codex`, `precision_plus`,
      #   `precision`, `smart`, and `economy`. Defaults to `smart`.
      #
      #   @return [Symbol, Deeprails::Models::DefendSubmitEventParams::RunMode]
      required :run_mode, enum: -> { Deeprails::DefendSubmitEventParams::RunMode }

      # @!attribute nametag
      #   An optional, user-defined tag for the event.
      #
      #   @return [String, nil]
      optional :nametag, String

      # @!method initialize(model_input:, model_output:, model_used:, run_mode:, nametag: nil, request_options: {})
      #   Some parameter documentations has been truncated, see
      #   {Deeprails::Models::DefendSubmitEventParams} for more details.
      #
      #   @param model_input [Deeprails::Models::DefendSubmitEventParams::ModelInput] A dictionary of inputs sent to the LLM to generate output. The dictionary must c
      #
      #   @param model_output [String] Output generated by the LLM to be evaluated.
      #
      #   @param model_used [String] Model ID used to generate the output, like `gpt-4o` or `o3`.
      #
      #   @param run_mode [Symbol, Deeprails::Models::DefendSubmitEventParams::RunMode] Run mode for the workflow event. The run mode allows the user to optimize for s
      #
      #   @param nametag [String] An optional, user-defined tag for the event.
      #
      #   @param request_options [Deeprails::RequestOptions, Hash{Symbol=>Object}]

      class ModelInput < Deeprails::Internal::Type::BaseModel
        # @!attribute user_prompt
        #   The user prompt used to generate the output.
        #
        #   @return [String]
        required :user_prompt, String

        # @!attribute context
        #   Any structured information that directly relates to the model’s input and
        #   expected output—e.g., the recent turn-by-turn history between an AI tutor and a
        #   student, facts or state passed through an agentic workflow, or other
        #   domain-specific signals your system already knows and wants the model to
        #   condition on.
        #
        #   @return [Array<Deeprails::Models::DefendSubmitEventParams::ModelInput::Context>, nil]
        optional :context,
                 -> { Deeprails::Internal::Type::ArrayOf[Deeprails::DefendSubmitEventParams::ModelInput::Context] }

        # @!attribute ground_truth
        #   The ground truth for evaluating the Ground Truth Adherence guardrail.
        #
        #   @return [String, nil]
        optional :ground_truth, String

        # @!attribute system_prompt
        #   The system prompt used to generate the output.
        #
        #   @return [String, nil]
        optional :system_prompt, String

        # @!method initialize(user_prompt:, context: nil, ground_truth: nil, system_prompt: nil)
        #   Some parameter documentations has been truncated, see
        #   {Deeprails::Models::DefendSubmitEventParams::ModelInput} for more details.
        #
        #   A dictionary of inputs sent to the LLM to generate output. The dictionary must
        #   contain a `user_prompt` field. For the ground_truth_adherence guardrail metric,
        #   `ground_truth` should be provided.
        #
        #   @param user_prompt [String] The user prompt used to generate the output.
        #
        #   @param context [Array<Deeprails::Models::DefendSubmitEventParams::ModelInput::Context>] Any structured information that directly relates to the model’s input and expect
        #
        #   @param ground_truth [String] The ground truth for evaluating the Ground Truth Adherence guardrail.
        #
        #   @param system_prompt [String] The system prompt used to generate the output.

        class Context < Deeprails::Internal::Type::BaseModel
          # @!attribute content
          #   The content of the message.
          #
          #   @return [String, nil]
          optional :content, String

          # @!attribute role
          #   The role of the speaker.
          #
          #   @return [String, nil]
          optional :role, String

          # @!method initialize(content: nil, role: nil)
          #   @param content [String] The content of the message.
          #
          #   @param role [String] The role of the speaker.
        end
      end

      # Run mode for the workflow event. The run mode allows the user to optimize for
      # speed, accuracy, and cost by determining which models are used to evaluate the
      # event. Available run modes include `precision_plus_codex`, `precision_plus`,
      # `precision`, `smart`, and `economy`. Defaults to `smart`.
      module RunMode
        extend Deeprails::Internal::Type::Enum

        PRECISION_PLUS_CODEX = :precision_plus_codex
        PRECISION_PLUS = :precision_plus
        PRECISION = :precision
        SMART = :smart
        ECONOMY = :economy

        # @!method self.values
        #   @return [Array<Symbol>]
      end
    end
  end
end
