# frozen_string_literal: true

module Deeprails
  module Models
    # @see Deeprails::Resources::Monitor#submit_event
    class MonitorSubmitEventParams < Deeprails::Internal::Type::BaseModel
      extend Deeprails::Internal::Type::RequestParameters::Converter
      include Deeprails::Internal::Type::RequestParameters

      # @!attribute monitor_id
      #
      #   @return [String]
      required :monitor_id, String

      # @!attribute model_input
      #   A dictionary of inputs sent to the LLM to generate output. The dictionary must
      #   contain a `user_prompt` field. For ground_truth_adherence guardrail metric,
      #   `ground_truth` should be provided.
      #
      #   @return [Deeprails::Models::MonitorSubmitEventParams::ModelInput]
      required :model_input, -> { Deeprails::MonitorSubmitEventParams::ModelInput }

      # @!attribute model_output
      #   Output generated by the LLM to be evaluated.
      #
      #   @return [String]
      required :model_output, String

      # @!attribute nametag
      #   An optional, user-defined tag for the event.
      #
      #   @return [String, nil]
      optional :nametag, String

      # @!attribute run_mode
      #   Run mode for the monitor event. The run mode allows the user to optimize for
      #   speed, accuracy, and cost by determining which models are used to evaluate the
      #   event. Available run modes (fastest to most thorough): `super_fast`, `fast`,
      #   `precision`, `precision_codex`, `precision_max`, and `precision_max_codex`.
      #   Defaults to `fast`. Note: `super_fast` does not support Web Search or File
      #   Search — if your monitor has these capabilities enabled, use a different run
      #   mode or edit the monitor to disable them.
      #
      #   @return [Symbol, Deeprails::Models::MonitorSubmitEventParams::RunMode, nil]
      optional :run_mode, enum: -> { Deeprails::MonitorSubmitEventParams::RunMode }

      # @!method initialize(monitor_id:, model_input:, model_output:, nametag: nil, run_mode: nil, request_options: {})
      #   Some parameter documentations has been truncated, see
      #   {Deeprails::Models::MonitorSubmitEventParams} for more details.
      #
      #   @param monitor_id [String]
      #
      #   @param model_input [Deeprails::Models::MonitorSubmitEventParams::ModelInput] A dictionary of inputs sent to the LLM to generate output. The dictionary must c
      #
      #   @param model_output [String] Output generated by the LLM to be evaluated.
      #
      #   @param nametag [String] An optional, user-defined tag for the event.
      #
      #   @param run_mode [Symbol, Deeprails::Models::MonitorSubmitEventParams::RunMode] Run mode for the monitor event. The run mode allows the user to optimize for sp
      #
      #   @param request_options [Deeprails::RequestOptions, Hash{Symbol=>Object}]

      class ModelInput < Deeprails::Internal::Type::BaseModel
        # @!attribute user_prompt
        #   The user prompt used to generate the output.
        #
        #   @return [String]
        required :user_prompt, String

        # @!attribute context
        #   Any structured information that directly relates to the model’s input and
        #   expected output—e.g., the recent turn-by-turn history between an AI tutor and a
        #   student, facts or state passed through an agentic workflow, or other
        #   domain-specific signals your system already knows and wants the model to
        #   condition on.
        #
        #   @return [Array<Deeprails::Models::MonitorSubmitEventParams::ModelInput::Context>, nil]
        optional :context,
                 -> { Deeprails::Internal::Type::ArrayOf[Deeprails::MonitorSubmitEventParams::ModelInput::Context] }

        # @!attribute ground_truth
        #   The ground truth for evaluating Ground Truth Adherence guardrail.
        #
        #   @return [String, nil]
        optional :ground_truth, String

        # @!attribute system_prompt
        #   The system prompt used to generate the output.
        #
        #   @return [String, nil]
        optional :system_prompt, String

        # @!method initialize(user_prompt:, context: nil, ground_truth: nil, system_prompt: nil)
        #   Some parameter documentations has been truncated, see
        #   {Deeprails::Models::MonitorSubmitEventParams::ModelInput} for more details.
        #
        #   A dictionary of inputs sent to the LLM to generate output. The dictionary must
        #   contain a `user_prompt` field. For ground_truth_adherence guardrail metric,
        #   `ground_truth` should be provided.
        #
        #   @param user_prompt [String] The user prompt used to generate the output.
        #
        #   @param context [Array<Deeprails::Models::MonitorSubmitEventParams::ModelInput::Context>] Any structured information that directly relates to the model’s input and expect
        #
        #   @param ground_truth [String] The ground truth for evaluating Ground Truth Adherence guardrail.
        #
        #   @param system_prompt [String] The system prompt used to generate the output.

        class Context < Deeprails::Internal::Type::BaseModel
          # @!attribute content
          #   The content of the message.
          #
          #   @return [String, nil]
          optional :content, String

          # @!attribute role
          #   The role of the speaker.
          #
          #   @return [String, nil]
          optional :role, String

          # @!method initialize(content: nil, role: nil)
          #   @param content [String] The content of the message.
          #
          #   @param role [String] The role of the speaker.
        end
      end

      # Run mode for the monitor event. The run mode allows the user to optimize for
      # speed, accuracy, and cost by determining which models are used to evaluate the
      # event. Available run modes (fastest to most thorough): `super_fast`, `fast`,
      # `precision`, `precision_codex`, `precision_max`, and `precision_max_codex`.
      # Defaults to `fast`. Note: `super_fast` does not support Web Search or File
      # Search — if your monitor has these capabilities enabled, use a different run
      # mode or edit the monitor to disable them.
      module RunMode
        extend Deeprails::Internal::Type::Enum

        SUPER_FAST = :super_fast
        FAST = :fast
        PRECISION = :precision
        PRECISION_CODEX = :precision_codex
        PRECISION_MAX = :precision_max
        PRECISION_MAX_CODEX = :precision_max_codex

        # @!method self.values
        #   @return [Array<Symbol>]
      end
    end
  end
end
