module Deeprails
  module Resources
    class Defend
      def create_workflow: (
        improvement_action: Deeprails::Models::DefendCreateWorkflowParams::improvement_action,
        name: String,
        threshold_type: Deeprails::Models::DefendCreateWorkflowParams::threshold_type,
        ?automatic_hallucination_tolerance_levels: ::Hash[Symbol, Deeprails::Models::DefendCreateWorkflowParams::automatic_hallucination_tolerance_level],
        ?custom_hallucination_threshold_values: ::Hash[Symbol, Float],
        ?description: String,
        ?file_search: ::Array[String],
        ?max_improvement_attempts: Integer,
        ?web_search: bool,
        ?request_options: Deeprails::request_opts
      ) -> Deeprails::DefendCreateResponse

      def retrieve_event: (
        String event_id,
        workflow_id: String,
        ?request_options: Deeprails::request_opts
      ) -> Deeprails::WorkflowEventDetailResponse

      def retrieve_workflow: (
        String workflow_id,
        ?limit: Integer,
        ?request_options: Deeprails::request_opts
      ) -> Deeprails::DefendResponse

      def submit_event: (
        String workflow_id,
        model_input: Deeprails::DefendSubmitEventParams::ModelInput,
        model_output: String,
        model_used: String,
        run_mode: Deeprails::Models::DefendSubmitEventParams::run_mode,
        ?nametag: String,
        ?request_options: Deeprails::request_opts
      ) -> Deeprails::WorkflowEventResponse

      def update_workflow: (
        String workflow_id,
        ?description: String,
        ?name: String,
        ?request_options: Deeprails::request_opts
      ) -> Deeprails::DefendUpdateResponse

      def initialize: (client: Deeprails::Client) -> void
    end
  end
end
