module Deeprails
  module Resources
    class Files
      def upload: (
        files: ::Array[String],
        ?request_options: Deeprails::request_opts
      ) -> Deeprails::FileResponse

      def initialize: (client: Deeprails::Client) -> void
    end
  end
end
