module Deeprails
  module Resources
    class Monitor
      def create: (
        name: String,
        ?description: String,
        ?request_options: Deeprails::request_opts
      ) -> Deeprails::APIResponse

      def retrieve: (
        String monitor_id,
        ?limit: Integer,
        ?request_options: Deeprails::request_opts
      ) -> Deeprails::Models::MonitorRetrieveResponse

      def update: (
        String monitor_id,
        ?description: String,
        ?monitor_status: Deeprails::Models::MonitorUpdateParams::monitor_status,
        ?name: String,
        ?request_options: Deeprails::request_opts
      ) -> Deeprails::APIResponse

      def submit_event: (
        String monitor_id,
        guardrail_metrics: ::Array[Deeprails::Models::MonitorSubmitEventParams::guardrail_metric],
        model_input: Deeprails::MonitorSubmitEventParams::ModelInput,
        model_output: String,
        ?model_used: String,
        ?nametag: String,
        ?run_mode: Deeprails::Models::MonitorSubmitEventParams::run_mode,
        ?request_options: Deeprails::request_opts
      ) -> Deeprails::Models::MonitorSubmitEventResponse

      def initialize: (client: Deeprails::Client) -> void
    end
  end
end
