module Deeprails
  class DefendCreateResponse = Deeprails::Models::DefendCreateResponse

  class DefendCreateWorkflowParams = Deeprails::Models::DefendCreateWorkflowParams

  class DefendResponse = Deeprails::Models::DefendResponse

  class DefendRetrieveEventParams = Deeprails::Models::DefendRetrieveEventParams

  class DefendRetrieveWorkflowParams = Deeprails::Models::DefendRetrieveWorkflowParams

  class DefendSubmitEventParams = Deeprails::Models::DefendSubmitEventParams

  class DefendUpdateResponse = Deeprails::Models::DefendUpdateResponse

  class DefendUpdateWorkflowParams = Deeprails::Models::DefendUpdateWorkflowParams

  class FileResponse = Deeprails::Models::FileResponse

  class FileUploadParams = Deeprails::Models::FileUploadParams

  class MonitorCreateParams = Deeprails::Models::MonitorCreateParams

  class MonitorCreateResponse = Deeprails::Models::MonitorCreateResponse

  class MonitorDetailResponse = Deeprails::Models::MonitorDetailResponse

  class MonitorEventDetailResponse = Deeprails::Models::MonitorEventDetailResponse

  class MonitorEventResponse = Deeprails::Models::MonitorEventResponse

  class MonitorRetrieveEventParams = Deeprails::Models::MonitorRetrieveEventParams

  class MonitorRetrieveParams = Deeprails::Models::MonitorRetrieveParams

  class MonitorSubmitEventParams = Deeprails::Models::MonitorSubmitEventParams

  class MonitorUpdateParams = Deeprails::Models::MonitorUpdateParams

  class MonitorUpdateResponse = Deeprails::Models::MonitorUpdateResponse

  class WorkflowEventDetailResponse = Deeprails::Models::WorkflowEventDetailResponse

  class WorkflowEventResponse = Deeprails::Models::WorkflowEventResponse
end
