# typed: strong

module Deeprails
  module Models
    class DefendSubmitEventParams < Deeprails::Internal::Type::BaseModel
      extend Deeprails::Internal::Type::RequestParameters::Converter
      include Deeprails::Internal::Type::RequestParameters

      OrHash =
        T.type_alias do
          T.any(
            Deeprails::DefendSubmitEventParams,
            Deeprails::Internal::AnyHash
          )
        end

      # A dictionary of inputs sent to the LLM to generate output. The dictionary must
      # contain at least `user_prompt` or `system_prompt` field. For the
      # ground_truth_adherence guardrail metric, `ground_truth` should be provided.
      sig { returns(Deeprails::DefendSubmitEventParams::ModelInput) }
      attr_reader :model_input

      sig do
        params(
          model_input: Deeprails::DefendSubmitEventParams::ModelInput::OrHash
        ).void
      end
      attr_writer :model_input

      # Output generated by the LLM to be evaluated.
      sig { returns(String) }
      attr_accessor :model_output

      # Model ID used to generate the output, like `gpt-4o` or `o3`.
      sig { returns(String) }
      attr_accessor :model_used

      # Run mode for the workflow event. The run mode allows the user to optimize for
      # speed, accuracy, and cost by determining which models are used to evaluate the
      # event. Available run modes include `precision_plus`, `precision`, `smart`, and
      # `economy`. Defaults to `smart`.
      sig { returns(Deeprails::DefendSubmitEventParams::RunMode::OrSymbol) }
      attr_accessor :run_mode

      # An optional, user-defined tag for the event.
      sig { returns(T.nilable(String)) }
      attr_reader :nametag

      sig { params(nametag: String).void }
      attr_writer :nametag

      sig do
        params(
          model_input: Deeprails::DefendSubmitEventParams::ModelInput::OrHash,
          model_output: String,
          model_used: String,
          run_mode: Deeprails::DefendSubmitEventParams::RunMode::OrSymbol,
          nametag: String,
          request_options: Deeprails::RequestOptions::OrHash
        ).returns(T.attached_class)
      end
      def self.new(
        # A dictionary of inputs sent to the LLM to generate output. The dictionary must
        # contain at least `user_prompt` or `system_prompt` field. For the
        # ground_truth_adherence guardrail metric, `ground_truth` should be provided.
        model_input:,
        # Output generated by the LLM to be evaluated.
        model_output:,
        # Model ID used to generate the output, like `gpt-4o` or `o3`.
        model_used:,
        # Run mode for the workflow event. The run mode allows the user to optimize for
        # speed, accuracy, and cost by determining which models are used to evaluate the
        # event. Available run modes include `precision_plus`, `precision`, `smart`, and
        # `economy`. Defaults to `smart`.
        run_mode:,
        # An optional, user-defined tag for the event.
        nametag: nil,
        request_options: {}
      )
      end

      sig do
        override.returns(
          {
            model_input: Deeprails::DefendSubmitEventParams::ModelInput,
            model_output: String,
            model_used: String,
            run_mode: Deeprails::DefendSubmitEventParams::RunMode::OrSymbol,
            nametag: String,
            request_options: Deeprails::RequestOptions
          }
        )
      end
      def to_hash
      end

      class ModelInput < Deeprails::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              Deeprails::DefendSubmitEventParams::ModelInput,
              Deeprails::Internal::AnyHash
            )
          end

        # The ground truth for evaluating Ground Truth Adherence guardrail.
        sig { returns(T.nilable(String)) }
        attr_reader :ground_truth

        sig { params(ground_truth: String).void }
        attr_writer :ground_truth

        # The system prompt used to generate the output.
        sig { returns(T.nilable(String)) }
        attr_reader :system_prompt

        sig { params(system_prompt: String).void }
        attr_writer :system_prompt

        # The user prompt used to generate the output.
        sig { returns(T.nilable(String)) }
        attr_reader :user_prompt

        sig { params(user_prompt: String).void }
        attr_writer :user_prompt

        # A dictionary of inputs sent to the LLM to generate output. The dictionary must
        # contain at least `user_prompt` or `system_prompt` field. For the
        # ground_truth_adherence guardrail metric, `ground_truth` should be provided.
        sig do
          params(
            ground_truth: String,
            system_prompt: String,
            user_prompt: String
          ).returns(T.attached_class)
        end
        def self.new(
          # The ground truth for evaluating Ground Truth Adherence guardrail.
          ground_truth: nil,
          # The system prompt used to generate the output.
          system_prompt: nil,
          # The user prompt used to generate the output.
          user_prompt: nil
        )
        end

        sig do
          override.returns(
            { ground_truth: String, system_prompt: String, user_prompt: String }
          )
        end
        def to_hash
        end
      end

      # Run mode for the workflow event. The run mode allows the user to optimize for
      # speed, accuracy, and cost by determining which models are used to evaluate the
      # event. Available run modes include `precision_plus`, `precision`, `smart`, and
      # `economy`. Defaults to `smart`.
      module RunMode
        extend Deeprails::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias do
            T.all(Symbol, Deeprails::DefendSubmitEventParams::RunMode)
          end
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        PRECISION_PLUS =
          T.let(
            :precision_plus,
            Deeprails::DefendSubmitEventParams::RunMode::TaggedSymbol
          )
        PRECISION =
          T.let(
            :precision,
            Deeprails::DefendSubmitEventParams::RunMode::TaggedSymbol
          )
        SMART =
          T.let(
            :smart,
            Deeprails::DefendSubmitEventParams::RunMode::TaggedSymbol
          )
        ECONOMY =
          T.let(
            :economy,
            Deeprails::DefendSubmitEventParams::RunMode::TaggedSymbol
          )

        sig do
          override.returns(
            T::Array[Deeprails::DefendSubmitEventParams::RunMode::TaggedSymbol]
          )
        end
        def self.values
        end
      end
    end
  end
end
