# typed: strong

module Deeprails
  module Models
    class DefendSubmitEventParams < Deeprails::Internal::Type::BaseModel
      extend Deeprails::Internal::Type::RequestParameters::Converter
      include Deeprails::Internal::Type::RequestParameters

      OrHash =
        T.type_alias do
          T.any(
            Deeprails::DefendSubmitEventParams,
            Deeprails::Internal::AnyHash
          )
        end

      # A dictionary of inputs sent to the LLM to generate output. This must contain a
      # `user_prompt` field and an optional `context` field. Additional properties are
      # allowed.
      sig { returns(Deeprails::DefendSubmitEventParams::ModelInput) }
      attr_reader :model_input

      sig do
        params(
          model_input: Deeprails::DefendSubmitEventParams::ModelInput::OrHash
        ).void
      end
      attr_writer :model_input

      # Output generated by the LLM to be evaluated.
      sig { returns(String) }
      attr_accessor :model_output

      # Model ID used to generate the output, like `gpt-4o` or `o3`.
      sig { returns(String) }
      attr_accessor :model_used

      # An optional, user-defined tag for the event.
      sig { returns(String) }
      attr_accessor :nametag

      # Run mode for the workflow event. The run mode allows the user to optimize for
      # speed, accuracy, and cost by determining which models are used to evaluate the
      # event. Available run modes include `precision_plus`, `precision`, `smart`, and
      # `economy`. Defaults to `smart`.
      sig { returns(Deeprails::DefendSubmitEventParams::RunMode::OrSymbol) }
      attr_accessor :run_mode

      sig do
        params(
          model_input: Deeprails::DefendSubmitEventParams::ModelInput::OrHash,
          model_output: String,
          model_used: String,
          nametag: String,
          run_mode: Deeprails::DefendSubmitEventParams::RunMode::OrSymbol,
          request_options: Deeprails::RequestOptions::OrHash
        ).returns(T.attached_class)
      end
      def self.new(
        # A dictionary of inputs sent to the LLM to generate output. This must contain a
        # `user_prompt` field and an optional `context` field. Additional properties are
        # allowed.
        model_input:,
        # Output generated by the LLM to be evaluated.
        model_output:,
        # Model ID used to generate the output, like `gpt-4o` or `o3`.
        model_used:,
        # An optional, user-defined tag for the event.
        nametag:,
        # Run mode for the workflow event. The run mode allows the user to optimize for
        # speed, accuracy, and cost by determining which models are used to evaluate the
        # event. Available run modes include `precision_plus`, `precision`, `smart`, and
        # `economy`. Defaults to `smart`.
        run_mode:,
        request_options: {}
      )
      end

      sig do
        override.returns(
          {
            model_input: Deeprails::DefendSubmitEventParams::ModelInput,
            model_output: String,
            model_used: String,
            nametag: String,
            run_mode: Deeprails::DefendSubmitEventParams::RunMode::OrSymbol,
            request_options: Deeprails::RequestOptions
          }
        )
      end
      def to_hash
      end

      class ModelInput < Deeprails::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              Deeprails::DefendSubmitEventParams::ModelInput,
              Deeprails::Internal::AnyHash
            )
          end

        sig { returns(String) }
        attr_accessor :user_prompt

        sig { returns(T.nilable(String)) }
        attr_reader :context

        sig { params(context: String).void }
        attr_writer :context

        # A dictionary of inputs sent to the LLM to generate output. This must contain a
        # `user_prompt` field and an optional `context` field. Additional properties are
        # allowed.
        sig do
          params(user_prompt: String, context: String).returns(T.attached_class)
        end
        def self.new(user_prompt:, context: nil)
        end

        sig { override.returns({ user_prompt: String, context: String }) }
        def to_hash
        end
      end

      # Run mode for the workflow event. The run mode allows the user to optimize for
      # speed, accuracy, and cost by determining which models are used to evaluate the
      # event. Available run modes include `precision_plus`, `precision`, `smart`, and
      # `economy`. Defaults to `smart`.
      module RunMode
        extend Deeprails::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias do
            T.all(Symbol, Deeprails::DefendSubmitEventParams::RunMode)
          end
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        PRECISION_PLUS =
          T.let(
            :precision_plus,
            Deeprails::DefendSubmitEventParams::RunMode::TaggedSymbol
          )
        PRECISION =
          T.let(
            :precision,
            Deeprails::DefendSubmitEventParams::RunMode::TaggedSymbol
          )
        SMART =
          T.let(
            :smart,
            Deeprails::DefendSubmitEventParams::RunMode::TaggedSymbol
          )
        ECONOMY =
          T.let(
            :economy,
            Deeprails::DefendSubmitEventParams::RunMode::TaggedSymbol
          )

        sig do
          override.returns(
            T::Array[Deeprails::DefendSubmitEventParams::RunMode::TaggedSymbol]
          )
        end
        def self.values
        end
      end
    end
  end
end
