# typed: strong

module Deeprails
  module Models
    class DefendSubmitAndStreamEventParams < Deeprails::Internal::Type::BaseModel
      extend Deeprails::Internal::Type::RequestParameters::Converter
      include Deeprails::Internal::Type::RequestParameters

      OrHash =
        T.type_alias do
          T.any(
            Deeprails::DefendSubmitAndStreamEventParams,
            Deeprails::Internal::AnyHash
          )
        end

      sig { returns(String) }
      attr_accessor :workflow_id

      # The input provided to the model (e.g., prompt, messages).
      sig { returns(T::Hash[Symbol, T.anything]) }
      attr_accessor :model_input

      # The output generated by the model to be evaluated.
      sig { returns(String) }
      attr_accessor :model_output

      # The model that generated the output (e.g., "gpt-4", "claude-3").
      sig { returns(String) }
      attr_accessor :model_used

      # The evaluation run mode. Streaming is supported on all run modes except
      # precision_max and precision_max_codex. Note: super_fast does not support Web
      # Search or File Search — if your workflow has these enabled, use a different run
      # mode or disable the capability on the workflow.
      sig do
        returns(Deeprails::DefendSubmitAndStreamEventParams::RunMode::OrSymbol)
      end
      attr_accessor :run_mode

      # Enable SSE streaming for real-time token feedback. Supported on all run modes
      # except precision_max and precision_max_codex.
      sig { returns(T.nilable(T::Boolean)) }
      attr_reader :stream

      sig { params(stream: T::Boolean).void }
      attr_writer :stream

      # Optional tag to identify this event.
      sig { returns(T.nilable(String)) }
      attr_reader :nametag

      sig { params(nametag: String).void }
      attr_writer :nametag

      sig do
        params(
          workflow_id: String,
          model_input: T::Hash[Symbol, T.anything],
          model_output: String,
          model_used: String,
          run_mode:
            Deeprails::DefendSubmitAndStreamEventParams::RunMode::OrSymbol,
          stream: T::Boolean,
          nametag: String,
          request_options: Deeprails::RequestOptions::OrHash
        ).returns(T.attached_class)
      end
      def self.new(
        workflow_id:,
        # The input provided to the model (e.g., prompt, messages).
        model_input:,
        # The output generated by the model to be evaluated.
        model_output:,
        # The model that generated the output (e.g., "gpt-4", "claude-3").
        model_used:,
        # The evaluation run mode. Streaming is supported on all run modes except
        # precision_max and precision_max_codex. Note: super_fast does not support Web
        # Search or File Search — if your workflow has these enabled, use a different run
        # mode or disable the capability on the workflow.
        run_mode:,
        # Enable SSE streaming for real-time token feedback. Supported on all run modes
        # except precision_max and precision_max_codex.
        stream: nil,
        # Optional tag to identify this event.
        nametag: nil,
        request_options: {}
      )
      end

      sig do
        override.returns(
          {
            workflow_id: String,
            model_input: T::Hash[Symbol, T.anything],
            model_output: String,
            model_used: String,
            run_mode:
              Deeprails::DefendSubmitAndStreamEventParams::RunMode::OrSymbol,
            stream: T::Boolean,
            nametag: String,
            request_options: Deeprails::RequestOptions
          }
        )
      end
      def to_hash
      end

      # The evaluation run mode. Streaming is supported on all run modes except
      # precision_max and precision_max_codex. Note: super_fast does not support Web
      # Search or File Search — if your workflow has these enabled, use a different run
      # mode or disable the capability on the workflow.
      module RunMode
        extend Deeprails::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias do
            T.all(Symbol, Deeprails::DefendSubmitAndStreamEventParams::RunMode)
          end
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        SUPER_FAST =
          T.let(
            :super_fast,
            Deeprails::DefendSubmitAndStreamEventParams::RunMode::TaggedSymbol
          )
        FAST =
          T.let(
            :fast,
            Deeprails::DefendSubmitAndStreamEventParams::RunMode::TaggedSymbol
          )
        PRECISION =
          T.let(
            :precision,
            Deeprails::DefendSubmitAndStreamEventParams::RunMode::TaggedSymbol
          )
        PRECISION_CODEX =
          T.let(
            :precision_codex,
            Deeprails::DefendSubmitAndStreamEventParams::RunMode::TaggedSymbol
          )

        sig do
          override.returns(
            T::Array[
              Deeprails::DefendSubmitAndStreamEventParams::RunMode::TaggedSymbol
            ]
          )
        end
        def self.values
        end
      end
    end
  end
end
