module Deeprails
  module Models
    type defend_submit_and_stream_event_params =
      {
        workflow_id: String,
        model_input: ::Hash[Symbol, top],
        model_output: String,
        model_used: String,
        run_mode: Deeprails::Models::DefendSubmitAndStreamEventParams::run_mode,
        stream: bool,
        nametag: String
      }
      & Deeprails::Internal::Type::request_parameters

    class DefendSubmitAndStreamEventParams < Deeprails::Internal::Type::BaseModel
      extend Deeprails::Internal::Type::RequestParameters::Converter
      include Deeprails::Internal::Type::RequestParameters

      attr_accessor workflow_id: String

      attr_accessor model_input: ::Hash[Symbol, top]

      attr_accessor model_output: String

      attr_accessor model_used: String

      attr_accessor run_mode: Deeprails::Models::DefendSubmitAndStreamEventParams::run_mode

      attr_reader stream: bool?

      def stream=: (bool) -> bool

      attr_reader nametag: String?

      def nametag=: (String) -> String

      def initialize: (
        workflow_id: String,
        model_input: ::Hash[Symbol, top],
        model_output: String,
        model_used: String,
        run_mode: Deeprails::Models::DefendSubmitAndStreamEventParams::run_mode,
        ?stream: bool,
        ?nametag: String,
        ?request_options: Deeprails::request_opts
      ) -> void

      def to_hash: -> {
        workflow_id: String,
        model_input: ::Hash[Symbol, top],
        model_output: String,
        model_used: String,
        run_mode: Deeprails::Models::DefendSubmitAndStreamEventParams::run_mode,
        stream: bool,
        nametag: String,
        request_options: Deeprails::RequestOptions
      }

      type run_mode = :super_fast | :fast | :precision | :precision_codex

      module RunMode
        extend Deeprails::Internal::Type::Enum

        SUPER_FAST: :super_fast
        FAST: :fast
        PRECISION: :precision
        PRECISION_CODEX: :precision_codex

        def self?.values: -> ::Array[Deeprails::Models::DefendSubmitAndStreamEventParams::run_mode]
      end
    end
  end
end
