module Deeprails
  module Models
    type defend_submit_event_params =
      {
        model_input: Deeprails::DefendSubmitEventParams::ModelInput,
        model_output: String,
        model_used: String,
        run_mode: Deeprails::Models::DefendSubmitEventParams::run_mode,
        nametag: String
      }
      & Deeprails::Internal::Type::request_parameters

    class DefendSubmitEventParams < Deeprails::Internal::Type::BaseModel
      extend Deeprails::Internal::Type::RequestParameters::Converter
      include Deeprails::Internal::Type::RequestParameters

      attr_accessor model_input: Deeprails::DefendSubmitEventParams::ModelInput

      attr_accessor model_output: String

      attr_accessor model_used: String

      attr_accessor run_mode: Deeprails::Models::DefendSubmitEventParams::run_mode

      attr_reader nametag: String?

      def nametag=: (String) -> String

      def initialize: (
        model_input: Deeprails::DefendSubmitEventParams::ModelInput,
        model_output: String,
        model_used: String,
        run_mode: Deeprails::Models::DefendSubmitEventParams::run_mode,
        ?nametag: String,
        ?request_options: Deeprails::request_opts
      ) -> void

      def to_hash: -> {
        model_input: Deeprails::DefendSubmitEventParams::ModelInput,
        model_output: String,
        model_used: String,
        run_mode: Deeprails::Models::DefendSubmitEventParams::run_mode,
        nametag: String,
        request_options: Deeprails::RequestOptions
      }

      type model_input =
        { ground_truth: String, system_prompt: String, user_prompt: String }

      class ModelInput < Deeprails::Internal::Type::BaseModel
        attr_reader ground_truth: String?

        def ground_truth=: (String) -> String

        attr_reader system_prompt: String?

        def system_prompt=: (String) -> String

        attr_reader user_prompt: String?

        def user_prompt=: (String) -> String

        def initialize: (
          ?ground_truth: String,
          ?system_prompt: String,
          ?user_prompt: String
        ) -> void

        def to_hash: -> {
          ground_truth: String,
          system_prompt: String,
          user_prompt: String
        }
      end

      type run_mode = :precision_plus | :precision | :smart | :economy

      module RunMode
        extend Deeprails::Internal::Type::Enum

        PRECISION_PLUS: :precision_plus
        PRECISION: :precision
        SMART: :smart
        ECONOMY: :economy

        def self?.values: -> ::Array[Deeprails::Models::DefendSubmitEventParams::run_mode]
      end
    end
  end
end
