module Deeprails
  module Models
    type defend_response =
      {
        automatic_hallucination_tolerance_levels: ::Hash[Symbol, Deeprails::Models::DefendResponse::automatic_hallucination_tolerance_level],
        created_at: Time,
        custom_hallucination_threshold_values: top,
        description: String,
        improvement_action: Deeprails::Models::DefendResponse::improvement_action,
        name: String,
        stats: Deeprails::DefendResponse::Stats,
        status: Deeprails::Models::DefendResponse::status,
        threshold_type: Deeprails::Models::DefendResponse::threshold_type,
        updated_at: Time,
        workflow_id: String
      }

    class DefendResponse < Deeprails::Internal::Type::BaseModel
      attr_reader automatic_hallucination_tolerance_levels: ::Hash[Symbol, Deeprails::Models::DefendResponse::automatic_hallucination_tolerance_level]?

      def automatic_hallucination_tolerance_levels=: (
        ::Hash[Symbol, Deeprails::Models::DefendResponse::automatic_hallucination_tolerance_level]
      ) -> ::Hash[Symbol, Deeprails::Models::DefendResponse::automatic_hallucination_tolerance_level]

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_reader custom_hallucination_threshold_values: top?

      def custom_hallucination_threshold_values=: (top) -> top

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader improvement_action: Deeprails::Models::DefendResponse::improvement_action?

      def improvement_action=: (
        Deeprails::Models::DefendResponse::improvement_action
      ) -> Deeprails::Models::DefendResponse::improvement_action

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader stats: Deeprails::DefendResponse::Stats?

      def stats=: (
        Deeprails::DefendResponse::Stats
      ) -> Deeprails::DefendResponse::Stats

      attr_reader status: Deeprails::Models::DefendResponse::status?

      def status=: (
        Deeprails::Models::DefendResponse::status
      ) -> Deeprails::Models::DefendResponse::status

      attr_reader threshold_type: Deeprails::Models::DefendResponse::threshold_type?

      def threshold_type=: (
        Deeprails::Models::DefendResponse::threshold_type
      ) -> Deeprails::Models::DefendResponse::threshold_type

      attr_reader updated_at: Time?

      def updated_at=: (Time) -> Time

      attr_reader workflow_id: String?

      def workflow_id=: (String) -> String

      def initialize: (
        ?automatic_hallucination_tolerance_levels: ::Hash[Symbol, Deeprails::Models::DefendResponse::automatic_hallucination_tolerance_level],
        ?created_at: Time,
        ?custom_hallucination_threshold_values: top,
        ?description: String,
        ?improvement_action: Deeprails::Models::DefendResponse::improvement_action,
        ?name: String,
        ?stats: Deeprails::DefendResponse::Stats,
        ?status: Deeprails::Models::DefendResponse::status,
        ?threshold_type: Deeprails::Models::DefendResponse::threshold_type,
        ?updated_at: Time,
        ?workflow_id: String
      ) -> void

      def to_hash: -> {
        automatic_hallucination_tolerance_levels: ::Hash[Symbol, Deeprails::Models::DefendResponse::automatic_hallucination_tolerance_level],
        created_at: Time,
        custom_hallucination_threshold_values: top,
        description: String,
        improvement_action: Deeprails::Models::DefendResponse::improvement_action,
        name: String,
        stats: Deeprails::DefendResponse::Stats,
        status: Deeprails::Models::DefendResponse::status,
        threshold_type: Deeprails::Models::DefendResponse::threshold_type,
        updated_at: Time,
        workflow_id: String
      }

      type automatic_hallucination_tolerance_level = :low | :medium | :high

      module AutomaticHallucinationToleranceLevel
        extend Deeprails::Internal::Type::Enum

        LOW: :low
        MEDIUM: :medium
        HIGH: :high

        def self?.values: -> ::Array[Deeprails::Models::DefendResponse::automatic_hallucination_tolerance_level]
      end

      type improvement_action = :regen | :fixit | :do_nothing

      module ImprovementAction
        extend Deeprails::Internal::Type::Enum

        REGEN: :regen
        FIXIT: :fixit
        DO_NOTHING: :do_nothing

        def self?.values: -> ::Array[Deeprails::Models::DefendResponse::improvement_action]
      end

      type stats =
        {
          outputs_below_threshold: Integer,
          outputs_improved: Integer,
          outputs_processed: Integer
        }

      class Stats < Deeprails::Internal::Type::BaseModel
        attr_reader outputs_below_threshold: Integer?

        def outputs_below_threshold=: (Integer) -> Integer

        attr_reader outputs_improved: Integer?

        def outputs_improved=: (Integer) -> Integer

        attr_reader outputs_processed: Integer?

        def outputs_processed=: (Integer) -> Integer

        def initialize: (
          ?outputs_below_threshold: Integer,
          ?outputs_improved: Integer,
          ?outputs_processed: Integer
        ) -> void

        def to_hash: -> {
          outputs_below_threshold: Integer,
          outputs_improved: Integer,
          outputs_processed: Integer
        }
      end

      type status = :inactive | :active

      module Status
        extend Deeprails::Internal::Type::Enum

        INACTIVE: :inactive
        ACTIVE: :active

        def self?.values: -> ::Array[Deeprails::Models::DefendResponse::status]
      end

      type threshold_type = :custom | :automatic

      module ThresholdType
        extend Deeprails::Internal::Type::Enum

        CUSTOM: :custom
        AUTOMATIC: :automatic

        def self?.values: -> ::Array[Deeprails::Models::DefendResponse::threshold_type]
      end
    end
  end
end
