module Deeprails
  module Models
    type defend_update_workflow_params =
      { description: String, name: String }
      & Deeprails::Internal::Type::request_parameters

    class DefendUpdateWorkflowParams < Deeprails::Internal::Type::BaseModel
      extend Deeprails::Internal::Type::RequestParameters::Converter
      include Deeprails::Internal::Type::RequestParameters

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (
        ?description: String,
        ?name: String,
        ?request_options: Deeprails::request_opts
      ) -> void

      def to_hash: -> {
        description: String,
        name: String,
        request_options: Deeprails::RequestOptions
      }
    end
  end
end
