module Deeprails
  module Models
    type evaluate_retrieve_params =
      {  } & Deeprails::Internal::Type::request_parameters

    class EvaluateRetrieveParams < Deeprails::Internal::Type::BaseModel
      extend Deeprails::Internal::Type::RequestParameters::Converter
      include Deeprails::Internal::Type::RequestParameters

      def initialize: (?request_options: Deeprails::request_opts) -> void

      def to_hash: -> { request_options: Deeprails::RequestOptions }
    end
  end
end
