module Deeprails
  module Models
    type file_response =
      { file_id: String, file_name: String, file_size: Integer }

    class FileResponse < Deeprails::Internal::Type::BaseModel
      attr_reader file_id: String?

      def file_id=: (String) -> String

      attr_reader file_name: String?

      def file_name=: (String) -> String

      attr_reader file_size: Integer?

      def file_size=: (Integer) -> Integer

      def initialize: (
        ?file_id: String,
        ?file_name: String,
        ?file_size: Integer
      ) -> void

      def to_hash: -> { file_id: String, file_name: String, file_size: Integer }
    end
  end
end
