module Deeprails
  module Models
    type monitor_detail_response =
      {
        capabilities: ::Array[Deeprails::MonitorDetailResponse::Capability],
        created_at: Time,
        evaluations: ::Array[Deeprails::MonitorDetailResponse::Evaluation],
        files: ::Array[Deeprails::MonitorDetailResponse::File],
        monitor_id: String,
        name: String,
        stats: Deeprails::MonitorDetailResponse::Stats,
        status: Deeprails::Models::MonitorDetailResponse::status,
        updated_at: Time,
        description: String
      }

    class MonitorDetailResponse < Deeprails::Internal::Type::BaseModel
      attr_accessor capabilities: ::Array[Deeprails::MonitorDetailResponse::Capability]

      attr_accessor created_at: Time

      attr_accessor evaluations: ::Array[Deeprails::MonitorDetailResponse::Evaluation]

      attr_accessor files: ::Array[Deeprails::MonitorDetailResponse::File]

      attr_accessor monitor_id: String

      attr_accessor name: String

      attr_accessor stats: Deeprails::MonitorDetailResponse::Stats

      attr_accessor status: Deeprails::Models::MonitorDetailResponse::status

      attr_accessor updated_at: Time

      attr_reader description: String?

      def description=: (String) -> String

      def initialize: (
        capabilities: ::Array[Deeprails::MonitorDetailResponse::Capability],
        created_at: Time,
        evaluations: ::Array[Deeprails::MonitorDetailResponse::Evaluation],
        files: ::Array[Deeprails::MonitorDetailResponse::File],
        monitor_id: String,
        name: String,
        stats: Deeprails::MonitorDetailResponse::Stats,
        status: Deeprails::Models::MonitorDetailResponse::status,
        updated_at: Time,
        ?description: String
      ) -> void

      def to_hash: -> {
        capabilities: ::Array[Deeprails::MonitorDetailResponse::Capability],
        created_at: Time,
        evaluations: ::Array[Deeprails::MonitorDetailResponse::Evaluation],
        files: ::Array[Deeprails::MonitorDetailResponse::File],
        monitor_id: String,
        name: String,
        stats: Deeprails::MonitorDetailResponse::Stats,
        status: Deeprails::Models::MonitorDetailResponse::status,
        updated_at: Time,
        description: String
      }

      type capability = { capability: String }

      class Capability < Deeprails::Internal::Type::BaseModel
        attr_reader capability: String?

        def capability=: (String) -> String

        def initialize: (?capability: String) -> void

        def to_hash: -> { capability: String }
      end

      type evaluation =
        {
          evaluation_status: Deeprails::Models::MonitorDetailResponse::Evaluation::evaluation_status,
          model_input: Deeprails::MonitorDetailResponse::Evaluation::ModelInput,
          model_output: String,
          run_mode: Deeprails::Models::MonitorDetailResponse::Evaluation::run_mode,
          created_at: Time,
          error_message: String,
          evaluation_result: ::Hash[Symbol, top],
          evaluation_total_cost: Float,
          guardrail_metrics: ::Array[Deeprails::Models::MonitorDetailResponse::Evaluation::guardrail_metric],
          nametag: String,
          progress: Integer
        }

      class Evaluation < Deeprails::Internal::Type::BaseModel
        attr_accessor evaluation_status: Deeprails::Models::MonitorDetailResponse::Evaluation::evaluation_status

        attr_accessor model_input: Deeprails::MonitorDetailResponse::Evaluation::ModelInput

        attr_accessor model_output: String

        attr_accessor run_mode: Deeprails::Models::MonitorDetailResponse::Evaluation::run_mode

        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_reader error_message: String?

        def error_message=: (String) -> String

        attr_reader evaluation_result: ::Hash[Symbol, top]?

        def evaluation_result=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

        attr_reader evaluation_total_cost: Float?

        def evaluation_total_cost=: (Float) -> Float

        attr_reader guardrail_metrics: ::Array[Deeprails::Models::MonitorDetailResponse::Evaluation::guardrail_metric]?

        def guardrail_metrics=: (
          ::Array[Deeprails::Models::MonitorDetailResponse::Evaluation::guardrail_metric]
        ) -> ::Array[Deeprails::Models::MonitorDetailResponse::Evaluation::guardrail_metric]

        attr_reader nametag: String?

        def nametag=: (String) -> String

        attr_reader progress: Integer?

        def progress=: (Integer) -> Integer

        def initialize: (
          evaluation_status: Deeprails::Models::MonitorDetailResponse::Evaluation::evaluation_status,
          model_input: Deeprails::MonitorDetailResponse::Evaluation::ModelInput,
          model_output: String,
          run_mode: Deeprails::Models::MonitorDetailResponse::Evaluation::run_mode,
          ?created_at: Time,
          ?error_message: String,
          ?evaluation_result: ::Hash[Symbol, top],
          ?evaluation_total_cost: Float,
          ?guardrail_metrics: ::Array[Deeprails::Models::MonitorDetailResponse::Evaluation::guardrail_metric],
          ?nametag: String,
          ?progress: Integer
        ) -> void

        def to_hash: -> {
          evaluation_status: Deeprails::Models::MonitorDetailResponse::Evaluation::evaluation_status,
          model_input: Deeprails::MonitorDetailResponse::Evaluation::ModelInput,
          model_output: String,
          run_mode: Deeprails::Models::MonitorDetailResponse::Evaluation::run_mode,
          created_at: Time,
          error_message: String,
          evaluation_result: ::Hash[Symbol, top],
          evaluation_total_cost: Float,
          guardrail_metrics: ::Array[Deeprails::Models::MonitorDetailResponse::Evaluation::guardrail_metric],
          nametag: String,
          progress: Integer
        }

        type evaluation_status =
          :in_progress | :completed | :canceled | :queued | :failed

        module EvaluationStatus
          extend Deeprails::Internal::Type::Enum

          IN_PROGRESS: :in_progress
          COMPLETED: :completed
          CANCELED: :canceled
          QUEUED: :queued
          FAILED: :failed

          def self?.values: -> ::Array[Deeprails::Models::MonitorDetailResponse::Evaluation::evaluation_status]
        end

        type model_input =
          { ground_truth: String, system_prompt: String, user_prompt: String }

        class ModelInput < Deeprails::Internal::Type::BaseModel
          attr_reader ground_truth: String?

          def ground_truth=: (String) -> String

          attr_reader system_prompt: String?

          def system_prompt=: (String) -> String

          attr_reader user_prompt: String?

          def user_prompt=: (String) -> String

          def initialize: (
            ?ground_truth: String,
            ?system_prompt: String,
            ?user_prompt: String
          ) -> void

          def to_hash: -> {
            ground_truth: String,
            system_prompt: String,
            user_prompt: String
          }
        end

        type run_mode = :precision_plus | :precision | :smart | :economy

        module RunMode
          extend Deeprails::Internal::Type::Enum

          PRECISION_PLUS: :precision_plus
          PRECISION: :precision
          SMART: :smart
          ECONOMY: :economy

          def self?.values: -> ::Array[Deeprails::Models::MonitorDetailResponse::Evaluation::run_mode]
        end

        type guardrail_metric =
          :correctness
          | :completeness
          | :instruction_adherence
          | :context_adherence
          | :ground_truth_adherence
          | :comprehensive_safety

        module GuardrailMetric
          extend Deeprails::Internal::Type::Enum

          CORRECTNESS: :correctness
          COMPLETENESS: :completeness
          INSTRUCTION_ADHERENCE: :instruction_adherence
          CONTEXT_ADHERENCE: :context_adherence
          GROUND_TRUTH_ADHERENCE: :ground_truth_adherence
          COMPREHENSIVE_SAFETY: :comprehensive_safety

          def self?.values: -> ::Array[Deeprails::Models::MonitorDetailResponse::Evaluation::guardrail_metric]
        end
      end

      type file = { file_id: String, file_name: String, file_size: Integer }

      class File < Deeprails::Internal::Type::BaseModel
        attr_reader file_id: String?

        def file_id=: (String) -> String

        attr_reader file_name: String?

        def file_name=: (String) -> String

        attr_reader file_size: Integer?

        def file_size=: (Integer) -> Integer

        def initialize: (
          ?file_id: String,
          ?file_name: String,
          ?file_size: Integer
        ) -> void

        def to_hash: -> {
          file_id: String,
          file_name: String,
          file_size: Integer
        }
      end

      type stats =
        {
          completed_evaluations: Integer,
          failed_evaluations: Integer,
          in_progress_evaluations: Integer,
          queued_evaluations: Integer,
          total_evaluations: Integer
        }

      class Stats < Deeprails::Internal::Type::BaseModel
        attr_reader completed_evaluations: Integer?

        def completed_evaluations=: (Integer) -> Integer

        attr_reader failed_evaluations: Integer?

        def failed_evaluations=: (Integer) -> Integer

        attr_reader in_progress_evaluations: Integer?

        def in_progress_evaluations=: (Integer) -> Integer

        attr_reader queued_evaluations: Integer?

        def queued_evaluations=: (Integer) -> Integer

        attr_reader total_evaluations: Integer?

        def total_evaluations=: (Integer) -> Integer

        def initialize: (
          ?completed_evaluations: Integer,
          ?failed_evaluations: Integer,
          ?in_progress_evaluations: Integer,
          ?queued_evaluations: Integer,
          ?total_evaluations: Integer
        ) -> void

        def to_hash: -> {
          completed_evaluations: Integer,
          failed_evaluations: Integer,
          in_progress_evaluations: Integer,
          queued_evaluations: Integer,
          total_evaluations: Integer
        }
      end

      type status = :active | :inactive

      module Status
        extend Deeprails::Internal::Type::Enum

        ACTIVE: :active
        INACTIVE: :inactive

        def self?.values: -> ::Array[Deeprails::Models::MonitorDetailResponse::status]
      end
    end
  end
end
