module Deeprails
  module Models
    type monitor_update_params =
      {
        monitor_id: String,
        description: String,
        file_search: ::Array[String],
        guardrail_metrics: ::Array[Deeprails::Models::MonitorUpdateParams::guardrail_metric],
        name: String,
        status: Deeprails::Models::MonitorUpdateParams::status,
        web_search: bool
      }
      & Deeprails::Internal::Type::request_parameters

    class MonitorUpdateParams < Deeprails::Internal::Type::BaseModel
      extend Deeprails::Internal::Type::RequestParameters::Converter
      include Deeprails::Internal::Type::RequestParameters

      attr_accessor monitor_id: String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader file_search: ::Array[String]?

      def file_search=: (::Array[String]) -> ::Array[String]

      attr_reader guardrail_metrics: ::Array[Deeprails::Models::MonitorUpdateParams::guardrail_metric]?

      def guardrail_metrics=: (
        ::Array[Deeprails::Models::MonitorUpdateParams::guardrail_metric]
      ) -> ::Array[Deeprails::Models::MonitorUpdateParams::guardrail_metric]

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader status: Deeprails::Models::MonitorUpdateParams::status?

      def status=: (
        Deeprails::Models::MonitorUpdateParams::status
      ) -> Deeprails::Models::MonitorUpdateParams::status

      attr_reader web_search: bool?

      def web_search=: (bool) -> bool

      def initialize: (
        monitor_id: String,
        ?description: String,
        ?file_search: ::Array[String],
        ?guardrail_metrics: ::Array[Deeprails::Models::MonitorUpdateParams::guardrail_metric],
        ?name: String,
        ?status: Deeprails::Models::MonitorUpdateParams::status,
        ?web_search: bool,
        ?request_options: Deeprails::request_opts
      ) -> void

      def to_hash: -> {
        monitor_id: String,
        description: String,
        file_search: ::Array[String],
        guardrail_metrics: ::Array[Deeprails::Models::MonitorUpdateParams::guardrail_metric],
        name: String,
        status: Deeprails::Models::MonitorUpdateParams::status,
        web_search: bool,
        request_options: Deeprails::RequestOptions
      }

      type guardrail_metric =
        :correctness
        | :completeness
        | :instruction_adherence
        | :context_adherence
        | :ground_truth_adherence
        | :comprehensive_safety

      module GuardrailMetric
        extend Deeprails::Internal::Type::Enum

        CORRECTNESS: :correctness
        COMPLETENESS: :completeness
        INSTRUCTION_ADHERENCE: :instruction_adherence
        CONTEXT_ADHERENCE: :context_adherence
        GROUND_TRUTH_ADHERENCE: :ground_truth_adherence
        COMPREHENSIVE_SAFETY: :comprehensive_safety

        def self?.values: -> ::Array[Deeprails::Models::MonitorUpdateParams::guardrail_metric]
      end

      type status = :active | :inactive

      module Status
        extend Deeprails::Internal::Type::Enum

        ACTIVE: :active
        INACTIVE: :inactive

        def self?.values: -> ::Array[Deeprails::Models::MonitorUpdateParams::status]
      end
    end
  end
end
